deployment:
  replica_count: 1
  deployment_name: "frontend-deployment"
  label_name: "frontend-label"
  container_name: "frontend-container"
  image: "martinsg8/onpk-appfrontend:1.0.0"
  container_port: "8086"
  REACT_APP_APIHOSTPORT: "10.1.2.3:80"

service:
  service_name: "frontend-service"
  type: "NodePort"
  label_name: "frontend-label"
  port: "8087"
  target_port: "8086"

ingress:
  ingress_name: "frontend-ingress"
  service_name: "frontend-service"
  port: 8087