# kubectl create secret generic dbconnectionparams-secret --from-literal=DB_HOST=192.168.100.100 --from-literal=DB_NAME=appdb --from-literal=DB_PASSWORD=mysecurepassword -o yaml --dry-run=client

apiVersion: v1
kind: Secret
metadata:
  name: dbconnectionparams-secret
data:
  DB_HOST: MTkyLjE2OC4xMDAuMTAw
  DB_NAME: YXBwZGI=
  DB_PASSWORD: bXlzZWN1cmVwYXNzd29yZA==

---
kind: Pod
apiVersion: v1
metadata:
  name: busybox-test-secret
  namespace: default
spec:
  containers:
    - name: busybox
      image: docker.io/busybox:latest
      command:
        - "/bin/sleep"
        - "10000"
      env:
      # we can use secrets as environment variables
      - name: DB_HOST
        valueFrom:
          secretKeyRef:
            name: dbconnectionparams-secret
            key: DB_HOST
      - name: DB_NAME
        valueFrom:
          secretKeyRef:
            name: dbconnectionparams-secret
            key: DB_NAME
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dbconnectionparams-secret
            key: DB_PASSWORD
      # we can mount secret as a volume as well
      volumeMounts:
      - name: dbparamsvolume
        mountPath: "/opt/secrets"
  volumes:
  - name: dbparamsvolume
    secret:
      secretName: dbconnectionparams-secret