# works on multi-node minikube cluster but requires:
# minikube addons enable volumesnapshots
# minikube addons enable csi-hostpath-driver
# minikube addons disable storage-provisioner
# minikube addons disable default-storageclass
# kubectl patch storageclass csi-hostpath-sc -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
  storageClassName: csi-hostpath-sc