apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  annotations:
    description: "MongoDB deployment."
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-label
  template:
    metadata:
      labels:
        app: mongodb-label
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "examplepassword"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-label
  annotations:
    description: "Backend deployment."
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-label
  template:
    metadata:
      labels:
        app: backend-label
    spec:
      containers:
      - name: backend-container
        image: martinsg8/onpk-appbackend:1.0.0
        ports:
        - containerPort: 12345
        env:
          - name: MONGO_USERNAME
            value: "admin"
          - name: MONGO_PASSWORD
            value: "examplepassword"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-1
  annotations:
    description: "Backend service 1."
spec:
  selector: 
    app: backend-label
  ports:
    - port: 4645
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-2
  labels:
    app: backend-service
  annotations:
    description: "Backend service 2."
spec:
  selector:
    app: backend-label
  ports:
    - port: 4655
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-label
  annotations:
    description: "Frontend deployment."
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-label
  template:
    metadata:
      labels:
        app: frontend-label
    spec:
      containers:
      - name: frontend-container
        image: martinsg8/onpk-appfrontend:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: REACT_APP_APIHOSTPORT
          value: "10.0.0.1:80"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    description: "Frontend service."
spec:
  selector:
    app: frontend-label
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    description: "Frontend ingress."
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /onpk-frontend-ingress
            backend:
              service:
                name: frontend-service
                port:
                  number: 8080
---
