apiVersion: v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  containers:
    - name: beck
      image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
      ports:
        - containerPort: 9080
      env:
        - name: MONGO_USERNAME
          value: "admin"
        - name: MONGO_PASSWORD
          value: "examplepassword"
---
apiVersion: v1
kind: Service
metadata:
  name: onpk-backend-service
spec:
  ports:
    - port: {{ .Values.backend.serviceNodePort.port }}
      protocol: TCP
      targetPort: {{ .Values.backend.serviceNodePort.targetPort }}
      nodePort: {{ .Values.backend.serviceNodePort.nodePort }}
  selector: 
    app: {{ .Chart.Name }}-be
  type: {{ .Values.backend.serviceNodePort.type }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceClusterIP.name }}
  labels:
    app: {{ .Chart.Name }}-be
spec:
  type: {{ .Values.backend.serviceClusterIP.type }}
  ports:
    - port: {{ .Values.backend.serviceClusterIP.port }}
      protocol: TCP
      targetPort: {{ .Values.backend.serviceClusterIP.targetPort }}
  clusterIP: {{ .Values.backend.serviceClusterIP.clusterIP }}
  selector:
    app: {{ .Chart.Name }}-be