# k apply -f <file-name>
# k delete -f <file-name>
apiVersion: v1
kind: Namespace
metadata:
  name: onpk-app
---
apiVersion: v1
kind: Deployment
metadata:
  name: onpk-frontend
  labels:
    app: frontend  
spec:
  replicas: 1
  containers:
    - name: onpk-frontend
      image: martinsg8/onpk-appfrontend:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: onpk-frontend-service
spec:
  selector:
    app: onpk-frontend
  ports:
    - port: 8080
  env:
    - name: REACT_APP_APIHOSTPORT
      value: "3535"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onpk-frontend-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: onpk-frontend-service
                port:
                  number: 8080
---
