apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.deployment_name }}
  labels:
    app: {{ .Values.deployment.label_name }}
  annotations:
    description: "Backend deployment."
spec:
  replicas: {{ .Values.deployment.replica_count }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label_name }}
    spec:
      containers:
      - name: {{ .Values.deployment.container_name}}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.container_port }}
        env:
          - name: MONGO_USERNAME
            value: {{ .Values.deployment.MONGO_USERNAME }}
          - name: MONGO_PASSWORD
            value: {{ .Values.deployment.MONGO_PASSWORD }}
---