apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.deployment-name }}
  labels:
    app: {{ .Values.deployment.label-name }}
  annotations:
    description: "Backend deployment."
spec:
  replicas: {{ .Values.deployment.replica-count }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label-name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label-name }}
    spec:
      containers:
      - name: {{ .Values.deployment.container-name}}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.container-port }}
        env:
          - name: MONGO_USERNAME
            value: {{ .Values.deployment.MONGO_USERNAME }}
          - name: MONGO_PASSWORD
            value: {{ .Values.deployment.MONGO_PASSWORD }}
---