apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.service_name }}
  annotations:
    description: "Backend service."
spec:
  type: {{ .Values.service.type }}
  selector: 
    app: {{ .Values.service.label_name }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.target_port }}
---