deployment:
  replica_count: 1
  deployment_name: backend-deployment
  label-name: backend-label
  container_name: backend-container
  image: martinsg8/onpk-appbackend:1.0.0
  container_port: 8082
  MONGO_USERNAME: admin
  MONGO_PASSWORD: examplepassword

service:
  service_name: backend-service
  type: ClusterIP
  label_name: backend-label
  port: 8083
  target_port: 8082

mongodb:
  replica_count: 1
  deployment_name: mongodb-deployment
  label_name: mongodb-label
  container_name: mongodb-container
  image: mongo:latest
  container_port: 12345
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: examplepassword