apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.deployment_name }}
  labels:
    app: {{ .Values.deployment.label_name }}
  annotations:
    description: "Frontend deployment."
spec:
  replicas: {{ .Values.deployment.replica_count }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label_name }}
    spec:
      containers:
      - name: {{ .Values.deployment.container_name }}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.container_port }}
        env:
        - name: REACT_APP_APIHOSTPORT
          value: {{ .Values.deployment.REACT_APP_APIHOSTPORT }}
---