apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.service_name }}
  annotations:
    description: "Frontend service."
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.service.label_name }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.target_port }}  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.ingress_name }}
  annotations:
    description: "Frontend ingress."
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Values.ingress.service_name }}
                port:
                  number: {{ .Values.ingress.port }}
---
